affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 3
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 13
symbolic.funs_name.0:
- - x
  - x
  - exp
  - x
  - sin
  - exp
  - x^2
  - sin
  - x
  - x
  - x
  - x
  - sin
  - exp
  - x
  - x
  - x
  - sin
  - x
  - sin
  - x
  - x
  - exp
  - x
  - sin
  - x
  - x^2
  - x
  - x
symbolic_enabled: true
width:
- - 29
  - 0
- - 1
  - 0
